export const strings = Object.freeze({
  path: {
    HOME: "/",
    GRAPHQL: "http://localhost:4000/graphql",
    LOGIN: "/login",
    SIGNUP: "/signup",
    SIGNOUT: "/signout",
    RECIPE_BOOK: "/recipebook",
    MY_RECIPES: "/myrecipes",
    MAILS: "/mails",
    MY_EVENTS: "/myevents",
    MY_PROFILE: "/myprofile",
    LINKEDIN: "https://www.linkedin.com/in/paul-del-priore-9b8b1114b/",
    SERVER_REQUEST: "http://localhost:4000/graphql",
  },
  navbar: {
    navType: {
      LOGO: "logo",
      LOGO_GET_STARTED: "logoGetStarted",
      LOGO_USER_LOGGED: "logoUserLogged",
      HOME_MENU: "homeMenu",
      GET_STARTED_MENU: "getStartedMenu",
      USER_LOGGED_MENU: "userLoggedMenu",
    },
    navHomeItems: {
      LOGO: "quoi manger ?",
      ABOUT: "en savoir plus",
      CONTACT: "contact",
    },
    navGetStartedItems: {
      LOGIN: "se connecter",
      SIGNUP: "s'inscrire",
    },
    navUserLoggedItems: {
      RECIPE_BOOK: "livre de recettes",
      MY_RECIPES: "mes recettes",
      MAILS: "boîte aux messages",
      MY_EVENTS: "mes événements",
      MY_PROFILE: "mon profil",
      SIGNOUT: "déconnexion",
    },
  },
  main: {
    MAIN_TEXT: "recherche une idée de plat ?",
    MAIN_SUB_TEXT: "tu es en bon endroit",
    BUTTON_TEXT: "commence ici",
  },
  about: {
    FIRST_AREA: "trouve ta recette",
    SECOND_AREA: "partage tes recettes",
    THIRD_AREA: "contacte d'autres passionnés",
    FOURTH_AREA: "organise tes événements",
  },
  contact: {
    FIRST_SECTION: "une question ?",
    BUTTON_TEXT: "envoyer",
    BUTTON_TEXT_LOADING: "j'envoie ...",
    FOOTER: "Paul Del Priore",
    SUBJECT: "sujet",
    EMAIL: "ton email",
    MESSAGE: "message",
  },
  login: {
    EMAIL: "email",
    PASSWORD: "mot de passe",
    BUTTON_TEXT: "connecte moi !",
    BUTTON_TEXT_LOADING: "je te connecte ...",
    FORGOT_PASSWORD: "mot de passe oublié ?",
  },
  signup: {
    USER_NAME: "nom d'utilisateur",
    EMAIL: "email",
    CONFIRM_EMAIL: "confirme ton email",
    PASSWORD: "mot de passe",
    BUTTON_TEXT: "inscris moi !",
    BUTTON_TEXT_LOADING: "je t'inscris ...",
    CHECK_EMAIL: "Compte enregistré avec succès. Confirme ton adresse email",
  },
  signupGoogle: {
    BUTTON_TEXT: "inscris moi !",
    GOOGLE_USER_CREATED: "google compte créé.",
  },
  remindPass: {
    EMAIL: "ton email",
    BUTTON_TEXT: "envoyer",
    BUTTON_TEXT_LOADING: "j'envoie ...",
    BUTTON_TEXT_CANCEL: "annuler",
  },
  logout: {
    LOGOUT: "je te déconnecte ...",
  },
  recipeBook: {
    BUTTON_NEW: "nouveautés",
    BUTTON_FAST_FOOD: "fast food",
    CAT_FAST_FOOD: "fast food",
    CAT_NEWS: "news",
  },
  recipeBookDetails: {
    DESCRIBE: "description:",
    INGREDIENTS: "ingrédients:",
  },
  rating: {
    DETAILS: "details",
    LIST: "list",
    COMMENT_RATE: "commentRate",
    RATE_AND_COMMENT: "rateAndComment",
    RATING_STARS: "ratingStars",
    COMMENT: "ton commentaire",
    BUTTON_TEXT: "ajoute",
    BUTTON_TEXT_LOADING: "j'ajoute ...",
    NOTE: "note",
    BUTTON_EDIT_TEXT: "modifie",
    BUTTON_EDIT_TEXT_LOADING: "je modifie ...",
    BUTTON_CANCEL_TEXT: "annule",
  },
});
