export const strings = Object.freeze({
  path: {
    HOME: "/",
    GRAPHQL: "https://localhost:4000/graphql",
    LOGIN: "/logowanie",
    SIGNUP: "/rejestracja",
    SIGNOUT: "/wylogowanie",
    RECIPE_BOOK: "/przepisy",
    MY_RECIPES: "/mojeprzepisy",
    MAILS: "/wiadomosci",
    MY_EVENTS: "/wydarzenia",
    MY_PROFILE: "/mojprofil",
    LINKEDIN: "https://www.linkedin.com/in/pawe%C5%82-del-priore-b55bbb1a8",
    SERVER_REQUEST: "https://localhost:4000/graphql",
    USER_PHOTO: "#",
    IMAGE_REQUEST: "https://localhost:4000",
    SERVER_PATH: "https://localhost:4000",
    MAP_REQUEST: "https://localhost:4000/heremaprender",
    GET_ADDRESSES: "https://localhost:4000/heremaprequest",
    GET_LOCATION: "https://localhost:4000/heremaplocation",
    GET_EMOJIS: "https://localhost:4000/emojis",
    GET_EMOJI_CAT: "https://localhost:4000/emojicategories",
  },
  navbar: {
    navType: {
      LOGO: "logo",
      LOGO_GET_STARTED: "logoGetStarted",
      LOGO_USER_LOGGED: "logoUserLogged",
      HOME_MENU: "homeMenu",
      GET_STARTED_MENU: "getStartedMenu",
      USER_LOGGED_MENU: "userLoggedMenu",
    },
    navHomeItems: {
      LOGO: "co jemy ?",
      MAIN: "główna",
      ABOUT: "zalety aplikacji",
      CONTACT: "kontakt",
    },
    navGetStartedItems: {
      LOGIN: "zaloguj się",
      SIGNUP: "załóż konto",
    },
    navUserLoggedItems: {
      RECIPE_BOOK: "przepisy",
      MY_RECIPES: "moje przepisy",
      MAILS: "wiadomości",
      MY_EVENTS: "wydarzenia kulinarne",
      MY_PROFILE: "mój profil",
      USER_PHOTO: "userPhoto",
      SIGNOUT: "wyloguj się",
    },
  },
  main: {
    MAIN_TEXT: "znasz fajny przepis ?",
    MAIN_SUB_TEXT: "podziel się nim",
    BUTTON_TEXT: "rozpocznij",
  },
  about: {
    FIRST_AREA: "wyszukuj przepisy",
    SECOND_AREA: "dziel się przepisami",
    THIRD_AREA: "nawiązuj kontakty z użytkownikami",
    FOURTH_AREA: "organizuj wydarzenia kulinarne",
  },
  contact: {
    FIRST_SECTION: "pytania ?",
    BUTTON_TEXT: "wyślij",
    BUTTON_TEXT_LOADING: "wysyłam ...",
    FOOTER: "Paweł Del Priore",
    SUBJECT: "temat *",
    SUBJECT_PLACEHOLDER: "temat",
    EMAIL: "twój email *",
    EMAIL_PLACEHOLDER: "email",
    MESSAGE: "wiadomość *",
    MESSAGE_PLACEHOLDER: "wiadomość",
  },
  login: {
    EMAIL: "twój email *",
    EMAIL_PLACEHOLDER: "email",
    PASSWORD: "hasło *",
    PASSWORD_PLACEHOLDER: "hasło",
    BUTTON_TEXT: "zaloguj się !",
    BUTTON_TEXT_LOADING: "loguję ...",
    FORGOT_PASSWORD: "zapomniałeś hasła ?",
  },
  signup: {
    USER_NAME: "nazwa użytkownika (min. 5 znaków) *",
    USER_NAME_PLACEHOLDER: "nazwa użytkownika",
    EMAIL: "twój email *",
    EMAIL_PLACEHOLDER: "email",
    CONFIRM_EMAIL: "potwierdź swój email *",
    CONFIRM_EMAIL_PLACEHOLDER: "potwierdź swój email",
    PASSWORD: "hasło (min. 8 znaków) *",
    PASSWORD_PLACEHOLDER: "hasło",
    BUTTON_TEXT: "załóż konto !",
    BUTTON_TEXT_LOADING: "rejestruję ...",
    CHECK_EMAIL:
      "Sprawdź swoją skrzynkę mailową i potwierdź że jesteś właścicielem wcześniej podanego adresu",
  },
  signupGoogle: {
    BUTTON_TEXT: "załóż konto !",
    GOOGLE_USER_CREATED: "konto założone",
  },
  remindPass: {
    EMAIL: "twój email *",
    EMAIL_PLACEHOLDER: "email",
    BUTTON_TEXT: "wyślij",
    BUTTON_TEXT_LOADING: "wysyłam ...",
    BUTTON_TEXT_CANCEL: "anuluj",
  },
  searchRecipe: {
    SEARCH: "znajdź przepis ...",
  },
  logout: {
    LOGOUT: "wylogowywuję ...",
  },
  recipeBook: {
    BUTTON_NEW: "nowości",
    CAT_NEWS: "news",
    BUTTON_FAST_FOOD: "fast food",
    CAT_FAST_FOOD: "fast food",
    BUTTON_LUNCH: "lunch",
    CAT_LUNCH: "lunch",
    BUTTON_DESSERT: "desery",
    CAT_DESSERT: "desserts",
    BUTTON_DRINKS: "drinki",
    CAT_DRINKS: "drinks",
    BUTTON_EVENING: "podwieczorek",
    CAT_EVENING: "evening",
    BUTTON_SALADES: "sałatki",
    CAT_SALADES: "salades",
  },
  recipeBookDetails: {
    DESCRIBE: "opis przygotowania:",
    INGREDIENTS: "składniki:",
    FOLLOW: "obserwuj autora przepisu",
    FOLLOW_LOADING: "proszę czekać ...",
    UNFOLLOW: "wyłącz obserwowanie",
  },
  rating: {
    DETAILS: "details",
    LIST: "list",
    COMMENT_RATE: "commentRate",
    RATE_AND_COMMENT: "rateAndComment",
    RATING_STARS: "ratingStars",
    COMMENT: "twój komentarz",
    BUTTON_TEXT: "dodaj",
    BUTTON_TEXT_LOADING: "dodaję ...",
    NOTE: "ocena",
    BUTTON_EDIT_TEXT: "popraw",
    BUTTON_EDIT_TEXT_LOADING: "poprawiam ...",
    BUTTON_CANCEL_TEXT: "anuluj",
  },
  myRecipes: {
    BUTTON_NEW_RECIPE: "nowy przepis",
    BUTTON_CORRECTION: "popraw",
    BUTTON_REMOVE: "usuń",
    BUTTON_REMOVE_LOADING: "usuwam ...",
    TITLE: "nazwa (max 21 znaków) *",
    TITLE_PLACEHOLDER: "nazwa",
    PICTURE: "obrazek",
    VIDEO: "nagranie wideo",
    VIDEO_PLACEHOLDER: "https://www.youtube.com/watch?v=xd",
    CATEGORY: "kategoria *",
    COOK_TIME: "czas przygotowania *",
    COOK_TIME_PLACEHOLDER: "w minutach",
    LOADING_IMAGE: "kompresuję ...",
    INGREDIENTS: "składniki *",
    INGREDIENTS_EX: "50ml oliwy,sól,pieprz, ...",
    DESCRIPTION: "opis przygotowania *",
    DESCRIPTION_PLACEHOLDER: "opis przygotowania",
    CHOOSE_PICTURE: "wybierz obrazek",
    CHOOSE_CATEGORY: "wybierz kategorię ...",
    MAX_PICTURE_SIZE: "max 9 MB",
    category: {
      LUNCH: "lunch",
      DESSERTS: "desery",
      DRINKS: "drinki",
      EVENING: "podwieczorek",
      SALADES: "sałatki",
      FAST_FOOD: "fast food",
    },
    inputName: {
      TITLE: "title",
      COOK_TIME: "cookTime",
      INGREDIENTS: "ingredients",
      DESCRIPTION: "description",
    },
    error: {
      VIDEO_URL_ERROR: "nieprawidłowy adres nagrania",
      IMAGE_SIZE_ERROR: "rozmiar obrazka przekracza 9 MB",
      IMAGE_UNACCEPTABLE: "obrazek niewłaściwy",
      IMAGE_FORMAT: "nieprawidłowy format obrazka",
      VIDEO_UNACCEPTABLE: "nagranie niewłaściwe",
    },
  },
  myProfile: {
    USER_NAME: "nazwa użytkownika (min. 5 znaków) *",
    USER_NAME_PLACEHOLDER: "nazwa użytkownika",
    BUTTON_TEXT_EDIT: "modyfikujemy ?",
    BUTTON_TEXT: "modyfikuj",
    BUTTON_TEXT_LOADING: "modyfikuję ...",
    BUTTON_EDIT_PASS: "zmieniamy hasło ?",
    CURRENT_PASS: "aktualne hasło *",
    CURRENT_PASS_PLACEHOLDER: "aktualne hasło",
    NEW_PASS: "nowe hasło *",
    NEW_PASS_PLACEHOLDER: "nowe hasło",
    CONFIRM_PASS: "potwierdź nowe hasło *",
    CONFIRME_PASS_PLACEHOLDER: "potwierdź nowe hasło",
    PASSWORD_CHANGED: "twoje hasło zostało zmienione",
    REMOVE_ACCOUNT: "na pewno chcesz usunąć konto ?",
    PHOTO: "zdjęcie",
    PICKER: "wybierz zdjęcie",
  },
  myEvents: {
    BUTTON_ALL: "lista wydarzeń",
    CAT_ALL: "all",
    BUTTON_MY_EVENTS: "moje wydarzenia",
    CAT_MY_EVENTS: "myEvents",
    BUTTON_EVENTS_JOINED: "uczestniczę",
    CAT_EVENTS_JOINED: "eventsJoined",
    BUTTON_NEW_EVENT: "nowe wydarzenie",
    TITLE: "nazwa (max 21 znaków) *",
    TITLE_PLACEHOLDER: "nazwa",
    PHOTO: "zdjęcie wydarzenia",
    ADDRESS: "miejsce *",
    ADDRESS_PREVIEW: "miejsce:",
    ADDRESS_PLACEHOLDER: "Plac Defilad 1, Warszawa",
    DESCRIPTION: "opis wydarzenia *",
    DESCRIPTION_PLACEHOLDER: "opis wydarzenia",
    AVAILABLE_PLACES: "ilość wolnych miejsc *",
    AVAILABLE_PLACES_PLACEHOLDER: "ilość wolnych miejsc",
    AVAILABLE_PLACES_PREVIEW: "wolne miejsca:",
    EVENT_DATE: "data wydarzenia *",
    EVENT_DATE_PLACEHOLDER: "data wydarzenia",
    TEL: "telefon kontaktowy *",
    TEL_PLACEHOLDER: "601100200",
    PARTICIPANTS_PREVIEW: "uczestnicy:",
    SEARCH_CITY: "miasto",
    SEARCH_DATE: "data wydarzenia",
    DATE_PLACEHOLDER: "01/12/2020, 10:00",
    SEARCH_DATE_PLACEHOLDER: "01/12/2020",
    BUTTON_JOIN: "weź udział",
    BUTTON_JOIN_LOADING: "zapisuję ...",
    BUTTON_UNJOIN: "zrezygnuj",
    BUTTON_UNJOIN_LOADING: "wypisuję ...",
    PICKER: "wybierz zdjęcie",
    FOLLOW: "obserwuj autora wydarzenia",
    error: {
      NO_SUGGESTIONS: "brak wydarzeń",
      NO_PARTICIPANTS: "narazie nikt się nie zapisał :(",
    },
    inputName: {
      TITLE: "title",
      DESCRIPTION: "description",
      AVAILABLE_PLACES: "availablePlaces",
      CITY: "city",
    },
    calendar: {
      days: {
        MON: "pon",
        TUE: "wt",
        WED: "sr",
        THU: "czw",
        FRI: "pia",
        SAT: "sob",
        SUN: "ndz",
      },
      months: {
        JAN: "styczeń",
        FEB: "luty",
        MAR: "marzec",
        APR: "kwiecień",
        MAY: "maj",
        JUN: "czerwiec",
        JUL: "lipiec",
        AUG: "sierpień",
        SEP: "wrzesień",
        OCT: "październik",
        NOV: "listopad",
        DEC: "grudzień",
      },
      HOUR: "godzina",
      error: {
        TIME_BEFORE: "wydarzenie może się rozpocząć najwcześniej o ",
      },
      button: {
        SAVE: "wybierz",
        EDIT: "zmień",
        CANCEL: "anuluj",
      },
    },
  },
  emojis: {
    categories: {
      EMOTIONS: "emocje",
      BODY: "gesty",
      ANIMALS: "przyroda",
      FOOD: "jedzenie",
      TRAVEL: "podróże",
      ACTIVITIES: "aktywność",
      OBJECTS: "obiekty",
      SYMBOLS: "symbole",
      FLAGS: "flagi",
    },
    categories_eng: {
      EMOTIONS: "smileys-emotion",
      BODY: "people-body",
      ANIMALS: "animals-nature",
      FOOD: "food-drink",
      TRAVEL: "travel-places",
      ACTIVITIES: "activities",
      OBJECTS: "objects",
      SYMBOLS: "symbols",
      FLAGS: "flags",
    },
  },
  mails: {
    BUTTON_NEW_MESSAGE: "nowa wiadomość",
    TO_PLACEHOLDER: "do kogo ?",
    CONTENT_PLACEHOLDER: "treść wiadomości",
    BUTTON_SEND: "wyślij",
    BUTTON_SEND_LOADING: "wysyłam ...",
    CLEAN_MESSAGE_INFO:
      "* Wiadomości będą usuwane automatycznie po około 3-ch dniach",
    error: {
      CONNECTION_ERROR: "problem z połączeniem sieciowym",
    },
  },
  error: {
    FETCH_ERROR: "problem z połączeniem sieciowym",
  },
});
